on:
  push:

env:
  PAT1: ${{ secrets.PAT1 }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  dump:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true
      - run: pnpm exec tsc scripts/collect-data.ts
      - run: node scripts/collect-data.js
      - run: |
          git add data.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "ci: Data dump update."
          git push
